### ISSUE TITLE
Glad to help

### ISSUE THREAD

**Issue by benjaminkomen** [otserv-tools/MonsterFromWiki#20]
Hey!
I saw you starred my TibiaWikiApi repository, so I took a look at what you made. Looks cool!
I'm glad my tool could be a building block for your project :)
If you have any suggestions or improvements, just let me know.
Cheers!

**Comment by giuinktse7** [comment]
Hey, thanks a ton for making the API and for checking my stuff out! I'll be sure to send suggestions your way if I think of anything 👍 

My ambition for this project is to use all available data from the wiki to generate monster files. But since I'm beginning on my master's thesis in a couple of days I will probably not be working much on Tibia-related stuff until summer.

Cheers!

**Comment by benjaminkomen** [comment]
Ok, good luck with your master's thesis :)
